name: CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Specify your Python version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set up Node.js and Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest # or specify a version

    - name: Install Node.js dependencies
      run: bun install

    - name: Run Linters and Formatters
      run: |
        # Add your Python linting/formatting commands here
        # Example:
        # pip install flake8
        # flake8 .
        # pip install black
        # black --check .

        # Add your Bun/TypeScript linting/formatting commands here
        # Example from package.json scripts (if any) or direct commands:
        # bun run lint
        # bun run format:check

        # Example using existing script:
        if [ -f scripts/lint-and-format.sh ]; then sh scripts/lint-and-format.sh; fi

    - name: Run Python Tests
      run: |
        # Add your Python test commands here
        # Example:
        # pip install pytest
        # pytest
        echo "Python tests would run here if configured."


    - name: Run TypeScript Tests
      run: |
        # Add your TypeScript test commands here
        # Example:
        # bun test
        echo "TypeScript tests would run here if configured."
